### ISSUE TITLE
FR6: Macronutrient Profile

### ISSUE THREAD

**Issue by josejasona** [WSU-4110/health.e#17]
|FR 6. Macronutrient Profile|
|---|
|**Goal**: Give the user a basic understanding of the macronutrients they should be consuming based on their goals (losing, maintain, or losing weight), and based on their Profile (Height, current weight)
**Stakeholders:** Users|
| Description: The user will input age, sex, height, weight, activity level as well as their weight goal. We will input these factors into the “Harris-Benedict Equation” This equation will yield a Basic Metabolic Rate, the amount of calories your body burns on a daily basis, and we can multiply the BMR with activity level to find the Daily Amount of Calories (DAC). Using this DAC we can then find out how many of each macro nutrient this person needs to either lose weight, maintain weight, or even gain weight.  |
| **Origin:** Discussed in first team meeting and refined in the second team meeting|
| **Version:** 1.0  |
|**Date:** 02/2/2023
|  **Priority:** 5 |

**Comment by JohnSullivanIV** [comment]
Able to update and add under progress tab.
