### ISSUE TITLE
FR2. App Tutorial 

### ISSUE THREAD

**Issue by MingranTan** [WSU-4110/health.e#2]
|FR2. App Tutorial|
|---|
|**Goal**: Application will provide users with tutorials about the application to help users understand the functions contained in the application faster.
**Stakeholders:** Application Users|
| **Description:** When users open the application for the first time and completes the account registration. Users may face lots of functions in the app, including creating personal files, making exercise plans, dietary standards, setting calender, and so on. Without help, users may not know where to start for a while, which will greatly discourage users' interest, and may shorten the life of applications. So, what developers need to do is after the users completes the registration. Use small windows to guide users step by step through various functions. It may first guide users to create their own body data, and then make exercise and diet plans step by step. Of course, developers will give option to users who are familiar with the app to skip the tutorial.|
| **Origin:** Team members proposed this feature at the first meeting and added it to the project file.|
| **Version:** 1.0.0 |
|**Date:** Feb-01-2022
|  **Priority:** 1 |

**Comment by JohnSullivanIV** [comment]
After development of the app we decided that a App Tutorial would be nice, but not needed due to simple design of the App.
