### ISSUE TITLE
NFR5: Macro Graph Update

### ISSUE THREAD

**Issue by mshul97** [WSU-4110/health.e#9]
|NFR5: Macro Graph Update|
|---|
|**Goal**: To update the macro graph upon completion of the assessment.
**Stakeholders:** Users|
| **Description:** This requirement is crucial for users who are overweight or obese as it helps them to track their progress and see the results of their efforts. An updated macro graph will help users to stay motivated and engaged with the app. Hence, it is imperative that the profile updates the macro graph upon completion of the assessment. Developers must ensure that the macro graph is updated in real-time and provides users with accurate information about their progress. |
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** 02/01/2023
|  **Priority:** 1 |

**Comment by JohnSullivanIV** [comment]
This was implemented into a pie graph under the progress tab.
